"""Add updated_at datetime field to TodoModel

Revision ID: cb225116e7f3
Revises: 7b12bbe59bd5
Create Date: 2021-08-05 23:17:40.878468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb225116e7f3'
down_revision = '7b12bbe59bd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_model', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo_model', 'updated_at')
    # ### end Alembic commands ###
